spring:
  application:
    name: practic
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/practic}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:P@ssw0rd}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    user:
      name: user
      password: 12345
